### ISSUE TITLE
After sleep mode on MacOS the utun8 interface is not released

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/wireguard-go#41]
After sleep mode on MacOS the utun8 interface is not released and the tunnel can't start.
Even if the client is stopped and restarted the client can't work.

Also it's impossible to remove the interface by hand, you need to reboot.

**Comment by julsemaan** [comment]
Is there a leftover process of wireguard or is the interface staying there without any process owning it ?

**Comment by fdurand** [comment]
Finally able to replicate.

Got: too many errors ,restart the client.

Client stopped but still have the "--master-controlled" process running.

**Comment by julsemaan** [comment]
I just tried it and I'm not getting the same behavior. Not sure if I need to wait longer for the issue to appear, I waited until it slept, then 5 minutes and woke up the computer. The tunnel was dead and was respawned by the master process and reconnected.

Perhaps related to the Mac OS version I'm running too

Can you provide more details on how we can replicate this consistently if that's a possibility

**Comment by fdurand** [comment]
It's after a long period the issue appear. I will retry it to give you an estimate of time.

**Comment by fdurand** [comment]
After a big nap

<img width="789" alt="Screen Shot 2021-01-06 at 3 43 31 PM" src="https://user-images.githubusercontent.com/1553962/103818912-64d47280-5037-11eb-8960-6c1d58b415ec.png">

`MBP-Inverse:amd64 inverse$ ./traywrapper 
Starting up
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection closed
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for initial status rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6970: connect: connection refused"
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update
Failed to contact tunnel for status update

`

I close the windows:

`
panic: open /Users/inverse/.wgenv-1609966517: permission denied

goroutine 1 [running]:
github.com/inverse-inc/packetfence/go/sharedutils.CheckError(...)
	/Users/inverse/go/pkg/mod/github.com/inverse-inc/packetfence/go@v0.0.0-20201214182518-cf77f7346ad3/sharedutils/util.go:120
github.com/inverse-inc/wireguard-go/binutils.init.0()
	/Users/inverse/sources/wireguard-go/binutils/set_env_darwin.go:18 +0x1c5
`

Click on the icon and open, no windows appear:

`
panic: open /Users/inverse/.wgenv-1609966671: permission denied

goroutine 1 [running]:
github.com/inverse-inc/packetfence/go/sharedutils.CheckError(...)
	/Users/inverse/go/pkg/mod/github.com/inverse-inc/packetfence/go@v0.0.0-20201214182518-cf77f7346ad3/sharedutils/util.go:120
github.com/inverse-inc/wireguard-go/binutils.init.0()
	/Users/inverse/sources/wireguard-go/binutils/set_env_darwin.go:18 +0x1c5
`

Quit the client:

`
Tray is exiting
Cleaning up environment file: /Users/inverse/.wgenv-1609955843
`

No icon anymore:

`
MBP-Inverse:amd64 inverse$ ps -edf|grep wire
    0  4643     1   0  2:10pm ttys000   56:16.38 /Users/inverse/sources/wireguard-go/amd64/wireguard /Users/inverse/.wgenv-1609955843 --master-controlled
MBP-Inverse:amd64 inverse$ ifconfig utun8
utun8: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1420
	inet 100.64.0.5 --> 100.127.255.255 netmask 0xffc00000
`

Kill wireguard:

`
MBP-Inverse:amd64 inverse$ sudo -s
Password:
bash-3.2# kill -9 4643
bash-3.2# ifconfig utun8
ifconfig: interface utun8 does not exist
`

Restart the client, then it is ok.

**Comment by julsemaan** [comment]
I think that this fix of the master process could fix it fb1fc882c5ade3524e9279ecae2f1b8007ee45d5

**Comment by julsemaan** [comment]
@fdurand confirmed that the sleep issue seems to be resolved now

**Comment by extrafu** [comment]
@julsemaan He has stopped sleeping on the job?

**Comment by fdurand** [comment]
Just to recorfirm, the laptop was in sleep mode all the night long and it recover by himself.
